version: "3"

services:
  db:
    image: mysql:8.0.29
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
