import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          foobar
        </h1>

        <Link href="/grade3">
          <a>３級</a>
        </Link>
      </main>
    </div>
  )
}

export default Home
